import type { PortalPreset } from "./types";

const KB = 1024;

const SUPPORTING_DOCS_SLOT = (maxSizeBytes: number) => ({
  id: "supportingDocs",
  label: "Supporting documents",
  helpText: "Any additional documents this portal asks for (certificates, ID proof, etc).",
  kind: "document" as const,
  required: false,
  multiple: true,
  targetFormat: "pdf" as const,
  maxSizeBytes,
});

const ADDRESS_PROOF_SLOT = (maxSizeBytes: number) => ({
  id: "addressProof",
  label: "Address proof",
  helpText: "Aadhaar, utility bill, or similar — photo or scan, either works.",
  kind: "document" as const,
  required: false,
  multiple: false,
  targetFormat: "pdf" as const,
  maxSizeBytes,
});

/**
 * Every number below was cross-checked against multiple current sources (cited per preset) as of
 * the `lastVerified` date. Government/exam portals republish specs with each notification cycle
 * and numbers occasionally shift by a few KB — always confirm against the current official
 * notification before submitting. Where sources disagreed slightly (e.g. RRB), the more commonly
 * cited figure was used and the discrepancy is noted.
 */
export const PORTAL_PRESETS: PortalPreset[] = [
  {
    slug: "passport-seva",
    name: "Passport Seva",
    agency: "Ministry of External Affairs, Government of India",
    description:
      "Photo and address proof for a fresh or reissue passport application via Passport Seva.",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent colour photo, plain white background, no glasses.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 630, height: 810 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 250 * KB,
      },
      ADDRESS_PROOF_SLOT(500 * KB),
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      {
        label: "Passport Seva photo/signature upload instructions (official PDF)",
        url: "https://assets.ctfassets.net/xxg4p8gt3sg6/65N7mZz0hfj57DM1VlnLA2/284bfc9bd711eda8a8564dad5019cc70/PASSPORT_SEVA_PHOTO_UPLOAD_INSTUCTIONS.pdf",
      },
      {
        label: "Passport Seva official FAQ",
        url: "https://services1.passportindia.gov.in/psp/FaqApplicationForm",
      },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "upsc",
    name: "UPSC Applications",
    agency: "Union Public Service Commission",
    description: "Photo and signature for UPSC's Common Application Form (Civil Services and others).",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent, formal, plain white background, face filling ~75% of the frame.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 350 },
        minSizeBytes: 20 * KB,
        maxSizeBytes: 300 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Sign 3 times on plain white paper in black ink, then upload one scan.",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 500 },
        minSizeBytes: 20 * KB,
        maxSizeBytes: 100 * KB,
      },
      SUPPORTING_DOCS_SLOT(1024 * KB),
    ],
    sources: [
      {
        label: "UPSC official photo & signature upload instructions",
        url: "https://upsconline.nic.in/ngrp/assets/PDF/instruction-photo-signature-upload-upsc.pdf",
      },
      {
        label: "UPSC photo & signature guidelines summary",
        url: "https://vajiramandravi.com/upsc-exam/upsc-photo-and-signature-guidelines/",
      },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "ssc",
    name: "SSC Exams",
    agency: "Staff Selection Commission",
    description: "Photo and signature for SSC exams (CGL, CHSL, GD, and similar).",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent colour photo (not older than 3 months), plain background.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 200, height: 230 },
        minSizeBytes: 20 * KB,
        maxSizeBytes: 50 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Running handwriting in black ink on white paper — not block letters.",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 140, height: 60 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 20 * KB,
      },
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      { label: "SSC GD photo & signature size guide", url: "https://testbook.com/news/ssc-gd-signature-photo-size/" },
      {
        label: "SSC CGL photo & signature size guide",
        url: "https://www.pw.live/ssc/exams/ssc-cgl-photo-and-signature-size-2026",
      },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "ibps",
    name: "IBPS Banking Exams",
    agency: "Institute of Banking Personnel Selection",
    description: "Photo and signature for IBPS PO, Clerk, SO, and RRB banking exams.",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent colour passport photo, light background.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 200, height: 230 },
        minSizeBytes: 20 * KB,
        maxSizeBytes: 50 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Natural running signature in black ink — not block/capital letters.",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 140, height: 60 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 20 * KB,
      },
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      { label: "IBPS PO/Clerk photo & signature guide", url: "https://signatureresize.in/ibps-po-clerk-photo-signature-guide-2026" },
      { label: "IBPS photo & signature requirements", url: "https://myexamphoto.in/blog/ibps-po-photo-size-guide/" },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "rrb",
    name: "RRB Railway Recruitment",
    agency: "Railway Recruitment Board",
    description: "Photo and signature for RRB exams (NTPC, Group D, ALP, JE, and similar).",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Plain white background — off-white/cream/grey backgrounds are commonly rejected.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 320, height: 240 },
        minSizeBytes: 30 * KB,
        maxSizeBytes: 70 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Dark ink on white unruled paper, running handwriting.",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 140, height: 60 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 40 * KB,
      },
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      { label: "RRB Group D photo & signature guidelines", url: "https://www.pw.live/railway/exams/rrb-group-d-photo-and-signature-size" },
      { label: "RRB NTPC photo & signature guide", url: "https://sarkaritools.org/blog/guide/rrb-ntpc-photo-and-signature-size/" },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "jee-main",
    name: "JEE Main (NTA)",
    agency: "National Testing Agency",
    description: "Photo and signature for JEE Main applications.",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent colour photo, 80% face visible (including ears), white background.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 450 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 200 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Scanned handwritten signature, black or blue ink, running handwriting.",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 150 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 100 * KB,
      },
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      { label: "JEE Main photo & signature guidelines", url: "https://collegedunia.com/exams/jee-main/photo-size-and-signature-guidelines" },
      { label: "JEE Main photo & signature rules", url: "https://engineering.careers360.com/articles/jee-main-photo-and-signature-guidelines" },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "neet",
    name: "NEET (NTA)",
    agency: "National Testing Agency",
    description: "Photo and signature for NEET (UG) applications.",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent passport-size colour photo, white/light background, 80% face visible.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 450 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 200 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Black ballpoint pen on white paper, running handwriting (not capitals).",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 150 },
        minSizeBytes: 4 * KB,
        maxSizeBytes: 30 * KB,
      },
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      { label: "NEET photo size & signature guidelines", url: "https://zollege.in/exams/neet/photo-size-and-signature-guidelines" },
      { label: "NEET photo & signature guidelines", url: "https://www.pw.live/neet/exams/photo-and-signature-upload-guidelines-for-neet-2026" },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "cuet",
    name: "CUET (NTA)",
    agency: "National Testing Agency",
    description: "Photo and signature for CUET (UG) applications.",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Recent colour photo, 80% face visible against a white background.",
        kind: "photo",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 200, height: 230 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 200 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Scanned handwritten signature on white paper.",
        kind: "signature",
        required: true,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 350, height: 150 },
        minSizeBytes: 10 * KB,
        maxSizeBytes: 50 * KB,
      },
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [
      { label: "CUET UG photo & signature upload guide", url: "https://www.signatureresize.in/cuet-ug-photo-signature-upload-guide-2026" },
      { label: "CUET photo size guidelines", url: "https://collegedunia.com/exams/cuet/photo-size-and-signature-guidelines" },
    ],
    lastVerified: "2026-07",
  },
  {
    slug: "custom",
    name: "Custom / Other Portal",
    agency: "State PSC, university admissions, scholarships, or any other portal",
    description:
      "State Public Service Commissions, university admissions, and scholarship portals each set their own requirements — there's no single official spec to hardcode. Enter the portal's stated limits yourself and the same pipeline runs against your numbers.",
    slots: [
      {
        id: "photo",
        label: "Photo",
        helpText: "Enter the target size and dimensions this portal asks for.",
        kind: "photo",
        required: false,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 200, height: 230 },
        maxSizeBytes: 50 * KB,
      },
      {
        id: "signature",
        label: "Signature",
        helpText: "Enter the target size and dimensions this portal asks for.",
        kind: "signature",
        required: false,
        multiple: false,
        targetFormat: "jpeg",
        targetDimensions: { width: 140, height: 60 },
        maxSizeBytes: 20 * KB,
      },
      ADDRESS_PROOF_SLOT(500 * KB),
      SUPPORTING_DOCS_SLOT(500 * KB),
    ],
    sources: [],
    lastVerified: "2026-07",
    isCustom: true,
  },
];

export function getPortalPreset(slug: string): PortalPreset | undefined {
  return PORTAL_PRESETS.find((preset) => preset.slug === slug);
}
