import {
  Minimize2,
  Combine,
  Scissors,
  FileType2,
  FileText,
  Images,
  FileImage,
  RotateCw,
  Trash2,
  ListOrdered,
  ImageDown,
  Maximize,
  Repeat,
  QrCode,
  Type,
  PencilLine,
} from "lucide-react";
import type { ToolConfig } from "@/types/tool";
import {
  MAX_FILES_DEFAULT,
  MAX_FILES_MULTI,
  MAX_FILES_BATCH_RENAME,
  MAX_FILE_SIZE_BYTES,
} from "@/lib/constants";

const PDF_MIME = ["application/pdf"];
const IMAGE_MIME = ["image/png", "image/jpeg", "image/webp"];

export const TOOLS: ToolConfig[] = [
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    shortDescription: "Shrink PDF file size",
    description:
      "Reduce the file size of your PDF for easier sharing and uploads.",
    category: "pdf",
    icon: Minimize2,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    shortDescription: "Combine multiple PDFs into one",
    description: "Merge multiple PDF files into a single document, in the order you choose.",
    category: "pdf",
    icon: Combine,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_MULTI,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    shortDescription: "Extract or separate pages",
    description: "Split a PDF into page ranges or extract every page as its own file.",
    category: "pdf",
    icon: Scissors,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    shortDescription: "Turn photos into a PDF",
    description: "Combine one or more images into a single PDF document.",
    category: "image",
    icon: FileImage,
    accept: [".png", ".jpg", ".jpeg", ".webp"],
    acceptMime: IMAGE_MIME,
    maxFiles: MAX_FILES_MULTI,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    shortDescription: "Convert DOCX to PDF",
    description: "Convert .docx Word documents into paginated PDF files.",
    category: "pdf",
    icon: FileType2,
    accept: [".docx"],
    acceptMime: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortDescription: "Convert PDF to DOCX",
    description: "Extract a PDF's text into an editable Word document.",
    category: "pdf",
    icon: FileText,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    shortDescription: "Export pages as images",
    description: "Convert each page of a PDF into a separate PNG image.",
    category: "pdf",
    icon: Images,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    shortDescription: "Fix page orientation",
    description: "Rotate every page in your PDF 90°, 180°, or 270°.",
    category: "pdf",
    icon: RotateCw,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "delete-pages",
    name: "Delete Pages",
    shortDescription: "Remove unwanted pages",
    description: "Delete specific pages from a PDF document.",
    category: "pdf",
    icon: Trash2,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: false,
  },
  {
    slug: "reorder-pages",
    name: "Reorder Pages",
    shortDescription: "Rearrange page order",
    description: "Drag and drop to reorder the pages in your PDF.",
    category: "pdf",
    icon: ListOrdered,
    accept: [".pdf"],
    acceptMime: PDF_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: false,
  },
  {
    slug: "compress-image",
    name: "Compress Image",
    shortDescription: "Shrink image file size",
    description: "Reduce the file size of JPEG, PNG, or WebP images.",
    category: "image",
    icon: ImageDown,
    accept: [".png", ".jpg", ".jpeg", ".webp"],
    acceptMime: IMAGE_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: false,
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    shortDescription: "Change image dimensions",
    description: "Resize images to exact pixel dimensions, including passport photo sizes.",
    category: "image",
    icon: Maximize,
    accept: [".png", ".jpg", ".jpeg", ".webp"],
    acceptMime: IMAGE_MIME,
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: false,
  },
  {
    slug: "convert-image",
    name: "Convert Image",
    shortDescription: "Switch image formats",
    description: "Convert between PNG, JPEG, WebP, and AVIF.",
    category: "image",
    icon: Repeat,
    accept: [".png", ".jpg", ".jpeg", ".webp", ".avif"],
    acceptMime: [...IMAGE_MIME, "image/avif"],
    maxFiles: MAX_FILES_DEFAULT,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "qr-generator",
    name: "QR Generator",
    shortDescription: "Create a QR code",
    description: "Generate a QR code from any text or URL.",
    category: "qr",
    icon: QrCode,
    accept: [],
    acceptMime: [],
    maxFiles: 0,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    shortDescription: "Count words & characters",
    description: "Count words, characters, and reading time instantly.",
    category: "text",
    icon: Type,
    accept: [],
    acceptMime: [],
    maxFiles: 0,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    shortDescription: "Turn plain text into a PDF",
    description: "Convert plain text into a nicely formatted PDF document.",
    category: "text",
    icon: FileText,
    accept: [],
    acceptMime: [],
    maxFiles: 0,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
  {
    slug: "batch-rename",
    name: "Batch Rename",
    shortDescription: "Rename many files at once",
    description:
      "Upload multiple files and rename them all at once with a sequential pattern, like Certificate-1, Certificate-2...",
    category: "files",
    icon: PencilLine,
    accept: [],
    acceptMime: [],
    maxFiles: MAX_FILES_BATCH_RENAME,
    maxFileSizeBytes: MAX_FILE_SIZE_BYTES,
    available: true,
  },
];

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return TOOLS.find((tool) => tool.slug === slug);
}

export const AVAILABLE_TOOLS = TOOLS.filter((tool) => tool.available);
